/** ZeroClaw runtime adapter — generates zeroclaw.toml config from an InternPackage */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { InternPackage } from '@internsmarket/core';
import { getInternPath } from './local-store-manager.js';

/** Builds a TOML string for ZeroClaw config (no external dep — simple enough for manual serialization) */
function buildToml(internPath: string, pkg: InternPackage): string {
  const name = pkg.aieos.identity?.names?.display
    ?? pkg.aieos.identity?.names?.given
    ?? pkg.manifest.id;

  return [
    '# Generated by InternsMarket — edit paths if your ZeroClaw install differs',
    `# Run: im apply ${pkg.manifest.id} --runtime=zeroclaw`,
    '',
    '[agent]',
    `name = "${name}"`,
    `description = "${pkg.manifest.description.replace(/"/g, '\\"')}"`,
    '',
    '[identity]',
    'format = "aieos"',
    `aieos_path = "${path.join(internPath, 'aieos.json').replace(/\\/g, '/')}"`,
    '',
    '[skills]',
    `path = "${path.join(internPath, 'skills').replace(/\\/g, '/')}"`,
    'auto_load = true',
    '',
    '[memory]',
    `seeds_path = "${path.join(internPath, 'memory-seeds').replace(/\\/g, '/')}"`,
    '',
  ].join('\n');
}

/** Writes config/zeroclaw.toml into the intern's install directory */
export function generateZeroClawConfig(pkg: InternPackage, installPath: string): void {
  const configDir = path.join(installPath, 'config');
  fs.mkdirSync(configDir, { recursive: true });
  const toml = buildToml(installPath, pkg);
  fs.writeFileSync(path.join(configDir, 'zeroclaw.toml'), toml, 'utf-8');
}

/**
 * Appends an include directive to ~/.zeroclaw/config.toml.
 * Throws if ZeroClaw is not installed at the expected path.
 */
export function applyToZeroClaw(internId: string): void {
  const internPath = getInternPath(internId);
  const tomlSrc = path.join(internPath, 'config', 'zeroclaw.toml');
  const zeroClawDir = path.join(os.homedir(), '.zeroclaw');

  if (!fs.existsSync(zeroClawDir)) {
    throw new Error(
      `ZeroClaw not found at ~/.zeroclaw\n` +
      `Install ZeroClaw first, then run this command again.`,
    );
  }

  if (!fs.existsSync(tomlSrc)) {
    throw new Error(
      `zeroclaw.toml not found for "${internId}". Re-install the intern first.`,
    );
  }

  const configToml = path.join(zeroClawDir, 'config.toml');
  const includeDirective = `\n# InternsMarket: ${internId}\ninclude = "${tomlSrc.replace(/\\/g, '/')}"\n`;

  // Avoid duplicate includes
  if (fs.existsSync(configToml)) {
    const existing = fs.readFileSync(configToml, 'utf-8');
    if (existing.includes(`# InternsMarket: ${internId}`)) return;
  }

  fs.appendFileSync(configToml, includeDirective, 'utf-8');
}
