/** OpenClaw runtime adapter — generates IDENTITY.md + SOUL.md + openclaw.yaml from InternPackage */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { InternPackage } from '@internsmarket/core';
import { compileIdentityMd, compileSoulMd } from '@internsmarket/core';
import { getInternPath } from './local-store-manager.js';

/** Builds a minimal openclaw.yaml config string */
function buildOpenClawYaml(internPath: string, pkg: InternPackage): string {
  const name = pkg.aieos.identity?.names?.display
    ?? pkg.aieos.identity?.names?.given
    ?? pkg.manifest.id;

  return [
    '# Generated by InternsMarket',
    `# Run: im apply ${pkg.manifest.id} --runtime=openclaw`,
    '',
    'agent:',
    `  name: "${name}"`,
    `  description: "${pkg.manifest.description.replace(/"/g, '\\"')}"`,
    '',
    'identity:',
    `  identity_file: "${path.join(internPath, 'config', 'IDENTITY.md').replace(/\\/g, '/')}"`,
    `  soul_file: "${path.join(internPath, 'config', 'SOUL.md').replace(/\\/g, '/')}"`,
    '',
    'skills:',
    `  path: "${path.join(internPath, 'skills').replace(/\\/g, '/')}"`,
    '',
    'memory:',
    `  seeds_path: "${path.join(internPath, 'memory-seeds').replace(/\\/g, '/')}"`,
    '',
  ].join('\n');
}

/** Writes config/openclaw.yaml + config/IDENTITY.md + config/SOUL.md to the install directory */
export function generateOpenClawConfig(pkg: InternPackage, installPath: string): void {
  const configDir = path.join(installPath, 'config');
  fs.mkdirSync(configDir, { recursive: true });

  fs.writeFileSync(
    path.join(configDir, 'openclaw.yaml'),
    buildOpenClawYaml(installPath, pkg),
    'utf-8',
  );
  fs.writeFileSync(
    path.join(configDir, 'IDENTITY.md'),
    compileIdentityMd(pkg.aieos),
    'utf-8',
  );
  fs.writeFileSync(
    path.join(configDir, 'SOUL.md'),
    compileSoulMd(pkg.aieos),
    'utf-8',
  );
}

/**
 * Copies IDENTITY.md and SOUL.md to ~/.openclaw/workspace/<intern-id>/.
 * Throws if OpenClaw workspace is not found.
 */
export function applyToOpenClaw(internId: string): void {
  const internPath = getInternPath(internId);
  const openClawWorkspace = path.join(os.homedir(), '.openclaw', 'workspace', internId);
  const openClawDir = path.join(os.homedir(), '.openclaw');

  if (!fs.existsSync(openClawDir)) {
    throw new Error(
      `OpenClaw not found at ~/.openclaw\n` +
      `Install OpenClaw first, then run this command again.`,
    );
  }

  fs.mkdirSync(openClawWorkspace, { recursive: true });

  for (const file of ['IDENTITY.md', 'SOUL.md', 'openclaw.yaml']) {
    const src = path.join(internPath, 'config', file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, path.join(openClawWorkspace, file));
    }
  }
}
