/** ZeroClaw runtime adapter — generates zeroclaw.toml config + workspace files from an InternPackage */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { InternPackage, AieosEntity, InternManifest } from '@internsmarket/core';
import {
  compileIdentityMd,
  compileSoulMd,
  fetchSkillRegistryIndex,
  resolveSkillDependencies,
  getSkillDownloadUrl,
  downloadSkillTgz,
  deployResolvedSkills,
  cleanStaleRegistrySkills,
} from '@internsmarket/core';
import { getInternPath } from './local-store-manager.js';

/** Builds a TOML string for ZeroClaw config (no external dep — simple enough for manual serialization) */
function buildToml(internPath: string, pkg: InternPackage): string {
  const name = pkg.aieos.identity?.names?.display
    ?? pkg.aieos.identity?.names?.given
    ?? pkg.manifest.id;

  return [
    '# Generated by InternsMarket — edit paths if your ZeroClaw install differs',
    `# Run: im apply ${pkg.manifest.id} --runtime=zeroclaw`,
    '',
    '[agent]',
    `name = "${name}"`,
    `description = "${pkg.manifest.description.replace(/"/g, '\\"')}"`,
    '',
    '[identity]',
    'format = "aieos"',
    `aieos_path = "${path.join(internPath, 'aieos.json').replace(/\\/g, '/')}"`,
    '',
    '[skills]',
    `path = "${path.join(internPath, 'skills').replace(/\\/g, '/')}"`,
    'auto_load = true',
    '',
    '[memory]',
    `seeds_path = "${path.join(internPath, 'memory-seeds').replace(/\\/g, '/')}"`,
    '',
  ].join('\n');
}

/** Writes config/zeroclaw.toml into the intern's install directory */
export function generateZeroClawConfig(pkg: InternPackage, installPath: string): void {
  const configDir = path.join(installPath, 'config');
  fs.mkdirSync(configDir, { recursive: true });
  const toml = buildToml(installPath, pkg);
  fs.writeFileSync(path.join(configDir, 'zeroclaw.toml'), toml, 'utf-8');
}

/** Reads and parses aieos.json from the intern's install directory */
function loadAieos(internPath: string): AieosEntity {
  const aieosPath = path.join(internPath, 'aieos.json');
  if (!fs.existsSync(aieosPath)) {
    throw new Error(`aieos.json not found at "${aieosPath}". Re-install the intern first.`);
  }
  return JSON.parse(fs.readFileSync(aieosPath, 'utf-8')) as AieosEntity;
}

/** Compiles SOUL.md + IDENTITY.md and writes to ~/.zeroclaw/workspace/<intern-id>/ */
function writeWorkspaceFiles(zeroClawDir: string, internId: string, aieos: AieosEntity): void {
  const workspaceDir = path.join(zeroClawDir, 'workspace', internId);
  fs.mkdirSync(workspaceDir, { recursive: true });

  fs.writeFileSync(path.join(workspaceDir, 'IDENTITY.md'), compileIdentityMd(aieos), 'utf-8');
  fs.writeFileSync(path.join(workspaceDir, 'SOUL.md'), compileSoulMd(aieos), 'utf-8');
}

/** Copies all skill directories from intern install to ~/.zeroclaw/skills/<intern-id>/ */
function copySkillsToRuntime(zeroClawDir: string, internId: string, internPath: string): void {
  const srcSkills = path.join(internPath, 'skills');
  if (!fs.existsSync(srcSkills)) return;

  const destSkills = path.join(zeroClawDir, 'skills', internId);
  fs.mkdirSync(destSkills, { recursive: true });

  for (const skillName of fs.readdirSync(srcSkills)) {
    const srcDir = path.join(srcSkills, skillName);
    if (!fs.statSync(srcDir).isDirectory()) continue;

    const destDir = path.join(destSkills, skillName);
    // Use recursive copy to preserve subdirectory structure within each skill
    fs.cpSync(srcDir, destDir, { recursive: true });
  }
}

/**
 * Generates workspace files (SOUL.md, IDENTITY.md), copies skills,
 * and appends an include directive to ~/.zeroclaw/config.toml.
 */
export function applyToZeroClaw(internId: string): void {
  const internPath = getInternPath(internId);
  const tomlSrc = path.join(internPath, 'config', 'zeroclaw.toml');
  const zeroClawDir = path.join(os.homedir(), '.zeroclaw');

  // Auto-create ~/.zeroclaw if it doesn't exist
  if (!fs.existsSync(zeroClawDir)) {
    fs.mkdirSync(zeroClawDir, { recursive: true });
  }

  if (!fs.existsSync(tomlSrc)) {
    throw new Error(
      `zeroclaw.toml not found for "${internId}". Re-install the intern first.`,
    );
  }

  // Compile AIEOS → workspace files (SOUL.md + IDENTITY.md)
  const aieos = loadAieos(internPath);
  writeWorkspaceFiles(zeroClawDir, internId, aieos);

  // Copy skills to ~/.zeroclaw/skills/<intern-id>/
  copySkillsToRuntime(zeroClawDir, internId, internPath);

  // Append config include directive (idempotent)
  const configToml = path.join(zeroClawDir, 'config.toml');
  const includeDirective = `\n# InternsMarket: ${internId}\ninclude = "${tomlSrc.replace(/\\/g, '/')}"\n`;

  if (fs.existsSync(configToml)) {
    const existing = fs.readFileSync(configToml, 'utf-8');
    if (existing.includes(`# InternsMarket: ${internId}`)) return;
  }

  fs.appendFileSync(configToml, includeDirective, 'utf-8');
}

/**
 * Reads manifest.json from intern install directory.
 * Returns null if not found or unreadable.
 */
function loadManifest(internPath: string): InternManifest | null {
  const manifestPath = path.join(internPath, 'manifest.json');
  if (!fs.existsSync(manifestPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as InternManifest;
  } catch {
    return null;
  }
}

/**
 * Enhanced apply: runs existing applyToZeroClaw (embedded skills),
 * then resolves and deploys any skillDependencies from the registry.
 * Backward compatible — interns without skillDependencies work exactly as before.
 */
export async function applyToZeroClawWithSkills(
  internId: string,
  onProgress?: (step: string) => void,
): Promise<void> {
  const internPath = getInternPath(internId);

  // Apply embedded skills + workspace files (existing sync flow)
  applyToZeroClaw(internId);

  const manifest = loadManifest(internPath);
  if (!manifest?.skillDependencies || Object.keys(manifest.skillDependencies).length === 0) {
    // No registry deps — nothing more to do
    return;
  }

  onProgress?.('Resolving skill dependencies...');

  const index = await fetchSkillRegistryIndex();
  const resolution = resolveSkillDependencies(manifest.skillDependencies, index);

  // Download tarballs to ~/.internsmarket/tgz-cache/
  const tgzCacheDir = path.join(os.homedir(), '.internsmarket', 'tgz-cache');
  fs.mkdirSync(tgzCacheDir, { recursive: true });

  for (const skill of resolution.resolved) {
    const tgzPath = path.join(tgzCacheDir, `${skill.name}-${skill.version}.tgz`);
    if (!fs.existsSync(tgzPath)) {
      const url = getSkillDownloadUrl(skill.name, skill.version);
      await downloadSkillTgz(url, tgzPath);
    }
  }

  onProgress?.('Deploying registry skills...');

  const zeroClawDir = path.join(os.homedir(), '.zeroclaw');
  const internSkillsDir = path.join(zeroClawDir, 'skills', internId);

  await deployResolvedSkills(resolution, internSkillsDir, tgzCacheDir);
  cleanStaleRegistrySkills(internSkillsDir, resolution);
}
